
parameters:
  learning_rate:
    value: 0.00032085084772518765
  batch_size:
    value: 64
  weight_decay:
    value: 0.00000432876575046065
  factor:
    value: 0.7494835558583441
  patience:
    value: 32
  epochs:
    value: 2000
  data_norm:
    "max"
  n_train:
    value: 4000
  n_val:
    value: 128
  n_test:
    value: 128
  params: "full" # can be 'full' or 'subset'
  fmpe_layers:
    value: 3
  fmpe_width:
    value: 1024
  latent_channels:
    value: 16
  noise_variance:
    value: 0.00
  save_model:
    value: False
    
    
  
    
# Add more parameters as needed
metric:
  goal: minimize
  name: test_loss_median
