
parameters:
  batch_size:
    value: 64
  epochs:
    value: 2001
  data_norm:
    "max"
  n_train:
    value: 4000
  n_val:
    value: 128
  n_test:
    value: 128
  params: "full" # can be 'full' or 'subset'
    
    
  
    
# Add more parameters as needed
metric:
  goal: minimize
  name: test_loss_median
