
parameters:
  epochs:
    value: 2001
  n_train:
    value: 8000
  n_val:
    value: 1000
  n_test:
    value: 1000
  batch_size:
    value: 64
  data_path:
    "../../_Data/ACB/"
    
    
# Add more parameters as needed
metric:
  goal: minimize
  name: test_loss_median
